# Source: https://github.com/airbnb/css/blob/master/.scss-lint.yml
# Converted to yml with: http://sasstools.github.io/make-sass-lint-config/
files:
  include: '**/*.scss'
  ignore:
    - 'node_modules/**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: ^(?!js-).*
      convention-explanation: should not be written in the form js-*
  extends-before-declarations: 0
  extends-before-mixins: 0
  function-name-format: 1
  id-name-format:
    - 1
    - convention: camel_case
  leading-zero: 0
  mixin-name-format: 1
  mixins-before-declarations: 0
  no-extends: 1
  no-qualifying-elements: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 1
  variable-name-format: 1
  space-before-brace:
    - 2
    - include: true
